# Generated by Django 4.0.4 on 2022-06-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_coursefeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefeedback',
            old_name='feedbak',
            new_name='feedback',
        ),
    ]
